### ISSUE TITLE
TrainingDataSmall and ValidationData folders

### ISSUE THREAD

**Issue by mikalovtch** [wyattpfeil/funcaptcha-solver-master#1]
TrainingDataSmall and ValidationData folder aren't found. Can you tell what should we put there, please?

**Comment by wyattpfeil** [comment]
This was actually a project I made using a tool by google called teachable machine. I suggest looking into it if you’re looking to use machine learning to solve funcaptchas. I 100% get the struggle when it comes to finding code to solve these guys, I spent months doing research to find even a little bit of help. This is probably not the best example for a solver to implement since it only has about a 60 percent accuracy. Some of the code in this project such as the opencv image processing might be useful for you if you go on to make your own one of these. I’m so sorry I’m not able to help. Enjoy the rest of your day/night.
